### ISSUE TITLE
Unable to find package 'VL.Rhino.3dm' Error

### ISSUE THREAD

**Issue by stephensmitchell** [wolfmoritzcramer/VL.Rhino.3dm#1]
Not experienced with vvvv nugets, got this error. 

![image](https://user-images.githubusercontent.com/5302428/182644074-b31d0327-c88a-49a7-b413-a661c172c12c.png)

**Comment by wolfmoritzcramer** [comment]
Ah, yes it is released as Alpha therefore you need to add the Version behind:
VL.Rhino.3dm -Version 0.1.7-alpha (is the current)
